partie_2/src/Entity/MailContact.php
<?php

namespace App\Entity;

use App\Repository\MailContactRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

#[ORM\Entity(repositoryClass: MailContactRepository::class)]
class MailContact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_envoi = null;

    #[ORM\Column(length: 255)]
    private ?string $objet = null;

    #[ORM\Column(length: 255)]
    private ?string $message = null;

    #[ORM\ManyToMany(targetEntity: Contact::class)]
    #[ORM\JoinTable(name: 'mail_educateur_contact')]
    private Collection $destinataires;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Educateur $expediteur = null;

    public function __construct()
    {
        $this->destinataires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEnvoi(): ?\DateTimeInterface
    {
        return $this->date_envoi;
    }

    public function setDateEnvoi(\DateTimeInterface $date_envoi): static
    {
        $this->date_envoi = $date_envoi;

        return $this;
    }

    public function getObjet(): ?string
    {
        return $this->objet;
    }

    public function setObjet(string $objet): static
    {
        $this->objet = $objet;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getDestinataires(): Collection
    {
        return $this->destinataires;
    }

    public function addDestinataire(Contact $destinataire): static
    {
        if (!$this->destinataires->contains($destinataire)) {
            $this->destinataires->add($destinataire);
        }

        return $this;
    }

    public function removeDestinataire(Contact $destinataire): static
    {
        $this->destinataires->removeElement($destinataire);

        return $this;
    }

    public function getExpediteur(): ?Educateur
    {
        return $this->expediteur;
    }

    public function setExpediteur(?Educateur $expediteur): static
    {
        $this->expediteur = $expediteur;

        return $this;
    }
}

partie_2/templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    {% block stylesheets %}
    {% endblock %}
</head>
<body>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <!-- Logo ou titre de la navbar -->
                <a class="navbar-brand" href="#">CLUB SPORTIF</a>

                <!-- Bouton pour afficher la navbar sur les petits écrans -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Contenu de la navbar -->
                <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_mail') }}">Mails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_list') }}">Listes</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_logout') }}">Se déconnecter</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center align-items-center mt-5">
        <div class="card mx-auto w-50">
            <p class="display-4 text-center font-weight-bold m-auto">BIENVENUE</p>
        </div>
    </div
{% endblock %}
{% block javascripts %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

partie_2/templates/contact.email.list.html.twig
<h1>Liste des emails envoyés aux educateurs</h1>
<table border="1">
    <thead>
    <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Email</th>
        <th>Numero de telephone</th>
    </tr>
    </thead>
    <tbody>
    {% for contact in contacts %}
        <tr>
            <td>{{ contact.nom }}</td>
            <td>{{ contact.prenom }}</td>
            <td>{{ contact.email }}</td>
            <td>{{ contact.numeroTel }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

partie_2/templates/educateur.email.list.html.twig
<h1>Mails envoyés</h1>
<a href="{{ path('app_send_mail_educateur') }}" class="btn btn-primary">Nouveau mail</a>
<table border="1">

    <thead>
    <tr>
        <th>Date d'envoie</th>
        <th>Objet</th>
        <th>Destinataires</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for mail in mails %}
        <tr>
            <td>{{ mail.dateEnvoi | date('d/m/Y') }}</td>
            <td>{{ mail.objet }}</td>
            <td>
                {% for destinataire in mail.destinataires %}
                    {{ destinataire.email }}{% if not loop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td><a href="{{ path('app_view_mail_educateur', {'id': mail.id}) }}" class="btn btn-primary">View</a></td>
            <td><a href="{{ path('app_delete_mail_educateur', {'id': mail.id}) }}" class="btn btn-danger">Delete</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>